# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: github_page ci

# ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    tags:
      - '*'
    #branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
    - run: npm run build
    - run: |
        cd dist
        cp index.html 404.html
        echo "" > .gitignore
        git init
        git config --local user.email "${{github.run_id}}+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -am "publish"
        git push --force --quiet https://${{github.actor}}:${{ github.token }}@github.com/${{github.repository}}.git master:gh-pages
        cd ../
        echo "everything ok!"
